# This is a sample autograder that uses cs251tk and gitlab
# to check that all files exist.
# Put together by Hawken Rives and Jason Dickmeyer

image: 'stodevx/cs251-toolkit:v2.7.2'
build:
  stage: build
  before_script:
    - shopt -s extglob
    - mkdir -p ./students/"$CI_PROJECT_NAME"
    - mv !(students) ./students/"$CI_PROJECT_NAME"
    - echo "$CI_PROJECT_NAME" > students.txt
    - git clone https://github.com/Jedmeyer/cs253-specs.git ./data
  script:
    - cs251tk -n --partial --no-progress --record $(ls students/"$CI_PROJECT_NAME"/ | grep 'hw') | tee results.out
    - >
      if grep -F '[31m' results.out;
      then
        INCOMPLETES=$(perl -l -ne 'print $1 while /\[31m(.+?).\[/g' < results.out);
        for hw in $INCOMPLETES; do
          cat logs/log-hw$hw.md
          for i in $(seq 1 20); do
            echo
          done
        done
        echo "Incomplete homeworks:"
        for hw in $INCOMPLETES; do
          echo "homework $hw"
        done
        echo "See StoGit website for full details."
        exit 1
      else
        echo "no issues"
      fi
